<?php

return [
    'tenant' => [
        [
            'key' => 'tenant-main',
            'label' => 'Ana Menü',
            'type' => 'group',
            'sort_order' => 10,
            'children' => [
                [
                    'key' => 'dashboard',
                    'label' => 'Yönetim Paneli',
                    'route' => 'admin.dashboard',
                    'icon' => 'check-circle',
                    'module_key' => 'core',
                    'feature_key' => 'dashboard',
                    'status' => 'active',
                    'sort_order' => 10,
                ],
                [
                    'key' => 'current-accounts',
                    'label' => 'Müşteriler / Cari Kartlar',
                    'route' => 'admin.current-accounts.index',
                    'icon' => 'check-circle',
                    'module_key' => 'current_accounts',
                    'feature_key' => 'current_account_cards',
                    'status' => 'active',
                    'sort_order' => 20,
                ],
                [
                    'key' => 'promotion-quotes',
                    'label' => 'Promosyon Teklifleri',
                    'route' => 'admin.promotion-quotes.index',
                    'icon' => 'check-circle',
                    'module_key' => 'order_flow',
                    'feature_key' => 'promotion_quotes',
                    'status' => 'active',
                    'sort_order' => 30,
                ],
                [
                    'key' => 'print-service-quotes',
                    'label' => 'Baskı Teklifleri',
                    'route' => 'admin.print-service-quotes.index',
                    'icon' => 'check-circle',
                    'module_key' => 'matbaa',
                    'feature_key' => 'print_quotes',
                    'status' => 'planned',
                    'sort_order' => 40,
                ],
                [
                    'key' => 'orders',
                    'label' => 'Siparişler',
                    'route' => 'admin.orders.index',
                    'icon' => 'check-circle',
                    'module_key' => 'order_flow',
                    'feature_key' => 'order_tracking',
                    'status' => 'active',
                    'sort_order' => 50,
                ],
                [
                    'key' => 'work-forms',
                    'label' => 'İş Formları',
                    'route' => 'admin.work-forms.index',
                    'icon' => 'check-circle',
                    'module_key' => 'work_forms',
                    'feature_key' => 'work_form_creation',
                    'status' => 'passive',
                    'sort_order' => 60,
                ],
            ],
        ],
        [
            'key' => 'tenant-catalog',
            'label' => 'Satış ve Katalog',
            'type' => 'group',
            'sort_order' => 20,
            'children' => [
                [
                    'key' => 'catalog',
                    'label' => 'Ürün ve Katalog',
                    'type' => 'accordion',
                    'icon' => 'check-circle',
                    'status' => 'active',
                    'group_slug' => 'tenant-catalog',
                    'children' => [
                        [
                            'key' => 'catalog-index',
                            'label' => 'Katalog Ürünleri',
                            'route' => 'admin.catalog.index',
                            'module_key' => 'advanced_catalog',
                            'feature_key' => 'product_variants',
                            'active_patterns' => [
                                'admin.catalog.index',
                                'admin.catalog.show',
                                'admin.catalog.product-panel',
                                'admin.catalog.supplier-products',
                                'admin.catalog.visibility',
                                'admin.catalog.warnings',
                            ],
                            'status' => 'active',
                            'sort_order' => 10,
                        ],
                        [
                            'key' => 'catalog-local-products',
                            'label' => 'Kendi Ürünlerim',
                            'route' => 'admin.catalog.local-products',
                            'module_key' => 'advanced_catalog',
                            'feature_key' => 'local_stock',
                            'active_patterns' => [
                                'admin.catalog.local-products',
                                'admin.catalog.local-products.*',
                            ],
                            'status' => 'active',
                            'sort_order' => 20,
                        ],
                    ],
                ],
                [
                    'key' => 'tenant-xml-export',
                    'label' => 'XML / CSV / Feed',
                    'route' => 'admin.product-data-hub.exports',
                    'icon' => 'check-circle',
                    'module_key' => 'xml_import_export',
                    'feature_key' => 'feed_outputs',
                    'status' => 'planned',
                    'sort_order' => 40,
                ],
            ],
        ],
        [
            'key' => 'tenant-operations',
            'label' => 'Operasyon',
            'type' => 'group',
            'sort_order' => 30,
            'children' => [
                [
                    'key' => 'graphics',
                    'label' => 'Grafik',
                    'route' => 'admin.graphics.index',
                    'icon' => 'check-circle',
                    'module_key' => 'graphics',
                    'feature_key' => 'graphic_queue',
                    'status' => 'active',
                    'sort_order' => 10,
                ],
                [
                    'key' => 'procurements',
                    'label' => 'Tedarik',
                    'route' => 'admin.procurements.index',
                    'icon' => 'check-circle',
                    'module_key' => 'procurement',
                    'feature_key' => 'procurement_queue',
                    'status' => 'active',
                    'sort_order' => 20,
                ],
                [
                    'key' => 'productions',
                    'label' => 'Üretim',
                    'route' => 'admin.productions.index',
                    'icon' => 'check-circle',
                    'module_key' => 'production',
                    'feature_key' => 'production_queue',
                    'status' => 'active',
                    'sort_order' => 30,
                ],
                [
                    'key' => 'deliveries',
                    'label' => 'Teslimat',
                    'route' => 'admin.deliveries.index',
                    'icon' => 'check-circle',
                    'module_key' => 'delivery',
                    'feature_key' => 'delivery_queue',
                    'status' => 'active',
                    'sort_order' => 40,
                ],
                [
                    'key' => 'finance',
                    'label' => 'Finans',
                    'route' => 'admin.finance.index',
                    'icon' => 'check-circle',
                    'permission_any' => [
                        'view_order_finance_summary',
                        'view_payment_details',
                        'manage_payments',
                        'mark_payments_received',
                    ],
                    'module_key' => 'finance',
                    'feature_key' => 'finance_summary',
                    'status' => 'active',
                    'sort_order' => 50,
                ],
            ],
        ],
        [
            'key' => 'tenant-optional',
            'label' => 'Ek Modüller',
            'type' => 'group',
            'sort_order' => 35,
            'children' => [
                [
                    'key' => 'customer-portal',
                    'label' => 'Müşteri Portalı',
                    'route' => 'admin.settings',
                    'active_patterns' => ['customer.portal.*'],
                    'icon' => 'check-circle',
                    'module_key' => 'customer_portal',
                    'feature_key' => 'customer_login',
                    'status' => 'active',
                    'sort_order' => 10,
                ],
                [
                    'key' => 'notification-center',
                    'label' => 'Bildirim Merkezi',
                    'route' => 'admin.notifications.index',
                    'active_patterns' => ['admin.notifications.*', 'admin.settings.notifications.*'],
                    'icon' => 'check-circle',
                    'module_key' => 'notification_center',
                    'status' => 'active',
                    'sort_order' => 20,
                ],
                [
                    'key' => 'reporting',
                    'label' => 'Raporlar',
                    'route' => 'admin.dashboard',
                    'icon' => 'check-circle',
                    'module_key' => 'reporting',
                    'feature_key' => 'sales_analytics',
                    'status' => 'passive',
                    'sort_order' => 30,
                ],
                [
                    'key' => 'api-access',
                    'label' => 'API',
                    'route' => 'admin.settings',
                    'active_patterns' => ['admin.api-access.*'],
                    'icon' => 'check-circle',
                    'module_key' => 'api_access',
                    'feature_key' => 'tenant_api_tokens',
                    'status' => 'passive',
                    'sort_order' => 40,
                ],
                [
                    'key' => 'production-qc',
                    'label' => 'Kalite Kontrol',
                    'route' => 'admin.productions.index',
                    'icon' => 'check-circle',
                    'module_key' => 'production_qc',
                    'feature_key' => 'qc_result',
                    'status' => 'planned',
                    'sort_order' => 50,
                ],
            ],
        ],
        [
            'key' => 'tenant-settings',
            'label' => 'Kurulum ve Ayarlar',
            'type' => 'group',
            'sort_order' => 40,
            'children' => [
                [
                    'key' => 'settings',
                    'label' => 'Kurulum Merkezi',
                    'route' => 'admin.settings',
                    'active_patterns' => ['admin.settings', 'admin.settings.company-profile.*'],
                    'icon' => 'check-circle',
                    'module_key' => 'tenant_settings',
                    'feature_key' => 'general_settings',
                    'status' => 'active',
                    'sort_order' => 10,
                ],
                [
                    'key' => 'my-package',
                    'label' => 'Paketim ve Kullanımım',
                    'route' => 'admin.my-package.index',
                    'active_patterns' => ['admin.my-package.*'],
                    'icon' => 'check-circle',
                    'module_key' => 'tenant_settings',
                    'permission' => 'manage_users',
                    'status' => 'active',
                    'sort_order' => 15,
                ],
                [
                    'key' => 'upgrade-requests',
                    'label' => 'Talep Merkezi',
                    'route' => 'admin.upgrade-requests.index',
                    'active_patterns' => ['admin.upgrade-requests.*'],
                    'icon' => 'check-circle',
                    'module_key' => 'tenant_settings',
                    'permission' => 'manage_users',
                    'status' => 'active',
                    'sort_order' => 18,
                ],
                [
                    'key' => 'print-settings',
                    'label' => 'Baskı Ayarları',
                    'route' => 'admin.settings.print-settings.index',
                    'icon' => 'check-circle',
                    'module_key' => 'print_settings',
                    'feature_key' => 'tenant_print_settings',
                    'status' => 'active',
                    'sort_order' => 20,
                ],
                [
                    'key' => 'user-management',
                    'label' => 'Kullanıcılar ve Roller',
                    'route' => 'admin.users.index',
                    'icon' => 'check-circle',
                    'module_key' => 'user_management',
                    'feature_key' => 'tenant_users',
                    'status' => 'active',
                    'sort_order' => 30,
                ],
            ],
        ],
    ],

    'super_admin' => [
        [
            'key' => 'super-main',
            'label' => 'Super Admin',
            'type' => 'group',
            'sort_order' => 10,
            'children' => [
                [
                    'key' => 'super-dashboard',
                    'label' => 'Super Admin Paneli',
                    'route' => 'admin.super.dashboard',
                    'icon' => 'check-circle',
                    'status' => 'active',
                    'sort_order' => 10,
                ],
                [
                    'key' => 'super-tenants',
                    'label' => 'Abone Firmalar',
                    'route' => 'admin.super.tenants.index',
                    'icon' => 'check-circle',
                    'status' => 'active',
                    'sort_order' => 20,
                ],
                [
                    'key' => 'super-signup-requests',
                    'label' => 'Başvurular',
                    'route' => 'admin.super.signup-requests.index',
                    'active_patterns' => [
                        'admin.super.signup-requests.*',
                        'admin.super.package-requests.*',
                    ],
                    'icon' => 'check-circle',
                    'status' => 'active',
                    'sort_order' => 25,
                ],
                [
                    'key' => 'super-upgrade-requests',
                    'label' => 'Abone Firma Talepleri',
                    'route' => 'admin.super.upgrade-requests.index',
                    'active_patterns' => [
                        'admin.super.upgrade-requests.*',
                    ],
                    'icon' => 'check-circle',
                    'status' => 'active',
                    'sort_order' => 27,
                ],
                [
                    'key' => 'super-packages',
                    'label' => 'Paketler',
                    'route' => 'admin.super.packages.index',
                    'icon' => 'check-circle',
                    'status' => 'active',
                    'sort_order' => 30,
                ],
                [
                    'key' => 'super-services',
                    'label' => 'Tenant Hizmetleri',
                    'route' => 'admin.super.services.index',
                    'active_patterns' => [
                        'admin.super.services.*',
                    ],
                    'icon' => 'check-circle',
                    'status' => 'active',
                    'sort_order' => 35,
                ],
                [
                    'key' => 'super-payment-providers',
                    'label' => 'Ödeme Altyapısı',
                    'route' => 'admin.super.payment-providers.index',
                    'active_patterns' => [
                        'admin.super.payment-providers.*',
                        'admin.super.payment-checkouts.*',
                    ],
                    'icon' => 'check-circle',
                    'status' => 'active',
                    'sort_order' => 38,
                ],
                [
                    'key' => 'super-modules',
                    'label' => 'Modüller',
                    'route' => 'admin.super.modules',
                    'icon' => 'check-circle',
                    'status' => 'planned',
                    'sort_order' => 40,
                ],
            ],
        ],
        [
            'key' => 'super-pdh',
            'label' => 'Product Data Hub',
            'type' => 'group',
            'sort_order' => 20,
            'children' => [
                [
                    'key' => 'super-product-data-hub',
                    'label' => 'Product Data Hub',
                    'type' => 'accordion',
                    'icon' => 'check-circle',
                    'status' => 'active',
                    'group_slug' => 'product-data-hub',
                    'children' => [
                        ['key' => 'super-pdh-heading-daily', 'label' => 'GÜNLÜK', 'type' => 'heading', 'status' => 'active', 'sort_order' => 5],
                        [
                            'key' => 'super-pdh-heading-status',
                            'label' => 'Durum Merkezi',
                            'type' => 'heading',
                            'description' => 'Kaynak, ürün, kategori, yayın ve senkron durumlarını tek ekranda izleyin.',
                            'status' => 'active',
                            'sort_order' => 5,
                        ],
                        [
                            'key' => 'super-pdh-overview',
                            'label' => 'Genel Bakış',
                            'route' => 'admin.super.product-data-hub.index',
                            'status' => 'active',
                            'sort_order' => 10,
                        ],
                        [
                            'key' => 'super-pipeline',
                            'label' => 'Akış Kontrol',
                            'route' => 'admin.super.product-data-hub.pipeline',
                            'status' => 'active',
                            'sort_order' => 20,
                        ],
                        [
                            'key' => 'super-pdh-heading-supplier-flows',
                            'label' => 'Tedarikçi Akışları',
                            'type' => 'heading',
                            'description' => 'XML/JSON/API kaynaklarını bağlayın, önizleyin, eşleme ve senkron durumlarını takip edin.',
                            'status' => 'active',
                            'sort_order' => 25,
                        ],
                        [
                            'key' => 'super-pdh-sources',
                            'label' => 'Tedarikçi Kaynakları',
                            'route' => 'admin.super.product-data-hub.sources.index',
                            'status' => 'active',
                            'sort_order' => 30,
                        ],
                        [
                            'key' => 'super-pdh-heading-product-pool',
                            'label' => 'Ürün Havuzu',
                            'type' => 'heading',
                            'description' => 'Tedarikçilerden gelen ürünleri, standart ürünleri, uyarıları ve kalite durumlarını inceleyin.',
                            'status' => 'active',
                            'sort_order' => 35,
                        ],
                        [
                            'key' => 'super-pdh-product-panel',
                            'label' => 'Ürün Paneli',
                            'route' => 'admin.super.product-data-hub.product-panel',
                            'status' => 'active',
                            'sort_order' => 40,
                        ],
                        [
                            'key' => 'super-standard-products',
                            'label' => 'Standart Ürünler (Teknik)',
                            'route' => 'admin.super.product-data-hub.standard-products.index',
                            'status' => 'active',
                            'sort_order' => 60,
                        ],
                        [
                            'key' => 'super-pdh-heading-category',
                            'label' => 'Kategori ve Özellikler',
                            'type' => 'heading',
                            'description' => 'Tedarikçi kategorilerini Prodelya standart kategorilerine bağlayın, özellik şablonlarını yönetin.',
                            'status' => 'active',
                            'sort_order' => 65,
                        ],
                        [
                            'key' => 'super-standard-categories',
                            'label' => 'Standart Kategori Ağacı',
                            'route' => 'admin.super.standard-categories.index',
                            'status' => 'active',
                            'sort_order' => 70,
                        ],
                        [
                            'key' => 'super-pdh-category-mappings',
                            'label' => 'Kategori Eşleme',
                            'route' => 'admin.super.product-data-hub.category-mappings.index',
                            'status' => 'active',
                            'sort_order' => 75,
                        ],
                        [
                            'key' => 'super-category-cleanup',
                            'label' => 'Kategori Temizlik',
                            'route' => 'admin.super.product-data-hub.category-cleanup.index',
                            'status' => 'active',
                            'sort_order' => 80,
                        ],
                        [
                            'key' => 'super-category-feature-templates',
                            'label' => 'Özellik Şablonları',
                            'route' => 'admin.super.product-data-hub.category-feature-templates.index',
                            'status' => 'active',
                            'sort_order' => 90,
                        ],
                        [
                            'key' => 'super-pdh-heading-catalog-publishing',
                            'label' => 'Abone Katalog Yayını',
                            'type' => 'heading',
                            'description' => 'Abone Firmalara açılan tedarikçileri ve katalog projection durumlarını yönetin.',
                            'status' => 'active',
                            'sort_order' => 95,
                        ],
                        [
                            'key' => 'super-pdh-catalog-output',
                            'label' => 'Abone Firma Katalog Çıkışları',
                            'route' => 'admin.super.product-data-hub.catalog-output',
                            'status' => 'active',
                            'sort_order' => 100,
                        ],
                        [
                            'key' => 'super-tenant-access',
                            'label' => 'Abone Firma Tedarikçi Erişimleri',
                            'route' => 'admin.super.tenant-supplier-access.index',
                            'status' => 'active',
                            'sort_order' => 110,
                        ],
                        [
                            'key' => 'super-pdh-heading-sync-reports',
                            'label' => 'Senkron / Raporlar',
                            'type' => 'heading',
                            'description' => 'Preview, import, standard build, projection ve hata raporlarını takip edin.',
                            'status' => 'active',
                            'sort_order' => 115,
                        ],
                        [
                            'key' => 'super-pdh-sync-reports',
                            'label' => 'Senkron ve Raporlar',
                            'route' => 'admin.super.product-data-hub.sources.sync-reports',
                            'status' => 'active',
                            'sort_order' => 120,
                        ],
                        [
                            'key' => 'super-pdh-heading-settings-maintenance',
                            'label' => 'Ayarlar ve Bakım',
                            'type' => 'heading',
                            'description' => 'Profil karşılaştırma, teknik bakım ve ileride storage/queue/search ayarlarını yönetin.',
                            'status' => 'active',
                            'sort_order' => 125,
                        ],
                        [
                            'key' => 'super-profile-comparison',
                            'label' => 'Profil Karşılaştırma',
                            'route' => 'admin.super.product-data-hub.profile-comparison',
                            'status' => 'active',
                            'sort_order' => 130,
                        ],
                    ],
                ],
            ],
        ],
        [
            'key' => 'super-settings-group',
            'label' => 'Super Ayarlar',
            'type' => 'group',
            'sort_order' => 30,
            'children' => [
                [
                    'key' => 'super-standard-print-types',
                    'label' => 'Standart Baskı Tipleri',
                    'route' => 'admin.super.standard-print-types.index',
                    'status' => 'planned',
                    'sort_order' => 10,
                ],
                [
                    'key' => 'super-settings',
                    'label' => 'Super Ayarlar',
                    'route' => 'admin.super.settings',
                    'status' => 'planned',
                    'sort_order' => 20,
                ],
            ],
        ],
    ],
];
