<?php

return [
    'status_values' => ['core', 'active', 'planned', 'passive', 'deprecated'],

    'modules' => [
        'core' => [
            'key' => 'core',
            'label' => 'Cekirdek Sistem',
            'name' => 'Cekirdek Sistem',
            'description' => 'Temel tenant erisimi, panel ve sistem omurgasi.',
            'category' => 'core',
            'status' => 'core',
            'is_core' => true,
            'mandatory' => true,
            'default_enabled' => true,
            'requires_package' => false,
            'parent_module' => null,
            'sort_order' => 10,
        ],
        'order_flow' => [
            'key' => 'order_flow',
            'label' => 'Teklif ve Siparis',
            'name' => 'Teklif ve Siparis',
            'description' => 'Promosyon ve baski tekliflerinden siparis akisina kadar temel satis omurgasi.',
            'category' => 'core',
            'status' => 'core',
            'is_core' => true,
            'mandatory' => true,
            'default_enabled' => true,
            'requires_package' => false,
            'parent_module' => null,
            'sort_order' => 20,
        ],
        'work_forms' => [
            'key' => 'work_forms',
            'label' => 'Is Formlari',
            'name' => 'Is Formlari',
            'description' => 'Siparisten is formu olusturma ve operasyon snapshot omurgasi.',
            'category' => 'core',
            'status' => 'core',
            'is_core' => true,
            'mandatory' => true,
            'default_enabled' => true,
            'requires_package' => false,
            'parent_module' => null,
            'sort_order' => 30,
        ],
        'current_accounts' => [
            'key' => 'current_accounts',
            'label' => 'Cari Kartlar',
            'name' => 'Cari Kartlar',
            'description' => 'Cari kartlar, cari hareketler ve ticari baglanti omurgasi.',
            'category' => 'core',
            'status' => 'core',
            'is_core' => true,
            'mandatory' => true,
            'default_enabled' => true,
            'requires_package' => false,
            'parent_module' => null,
            'sort_order' => 40,
        ],
        'finance' => [
            'key' => 'finance',
            'label' => 'Finans',
            'name' => 'Finans',
            'description' => 'Tahsilat, ozetler ve temel finansal gorunumler.',
            'category' => 'core',
            'status' => 'core',
            'is_core' => true,
            'mandatory' => true,
            'default_enabled' => true,
            'requires_package' => false,
            'parent_module' => null,
            'sort_order' => 50,
        ],
        'procurement' => [
            'key' => 'procurement',
            'label' => 'Tedarik',
            'name' => 'Tedarik',
            'description' => 'Tedarikci talep, satin alma ve tedarik operasyonlari.',
            'category' => 'operations',
            'status' => 'core',
            'is_core' => true,
            'mandatory' => true,
            'default_enabled' => true,
            'requires_package' => false,
            'parent_module' => null,
            'sort_order' => 60,
        ],
        'graphics' => [
            'key' => 'graphics',
            'label' => 'Grafik',
            'name' => 'Grafik',
            'description' => 'Per-print grafik operasyonlari ve musteriye gorunen dosya akislari.',
            'category' => 'operations',
            'status' => 'core',
            'is_core' => true,
            'mandatory' => true,
            'default_enabled' => true,
            'requires_package' => false,
            'parent_module' => null,
            'sort_order' => 70,
        ],
        'production' => [
            'key' => 'production',
            'label' => 'Uretim',
            'name' => 'Uretim',
            'description' => 'Per-print uretim, readiness ve fason operasyon omurgasi.',
            'category' => 'operations',
            'status' => 'core',
            'is_core' => true,
            'mandatory' => true,
            'default_enabled' => true,
            'requires_package' => false,
            'parent_module' => null,
            'sort_order' => 80,
        ],
        'delivery' => [
            'key' => 'delivery',
            'label' => 'Teslimat',
            'name' => 'Teslimat',
            'description' => 'Paket, koli ve teslimat operasyonlari.',
            'category' => 'operations',
            'status' => 'core',
            'is_core' => true,
            'mandatory' => true,
            'default_enabled' => true,
            'requires_package' => false,
            'parent_module' => null,
            'sort_order' => 90,
        ],
        'print_settings' => [
            'key' => 'print_settings',
            'label' => 'Baski Ayarlari',
            'name' => 'Baski Ayarlari',
            'description' => 'Standart baski tipleri, tenant baski ayarlari ve setup ihtiyaclari.',
            'category' => 'core',
            'status' => 'core',
            'is_core' => true,
            'mandatory' => true,
            'default_enabled' => true,
            'requires_package' => false,
            'parent_module' => null,
            'sort_order' => 100,
        ],
        'user_management' => [
            'key' => 'user_management',
            'label' => 'Kullanici ve Yetki',
            'name' => 'Kullanici ve Yetki',
            'description' => 'Tenant kullanici, rol ve permission yonetimi.',
            'category' => 'core',
            'status' => 'core',
            'is_core' => true,
            'mandatory' => true,
            'default_enabled' => true,
            'requires_package' => false,
            'parent_module' => null,
            'sort_order' => 110,
        ],
        'tenant_settings' => [
            'key' => 'tenant_settings',
            'label' => 'Tenant Ayarlari',
            'name' => 'Tenant Ayarlari',
            'description' => 'Genel tenant ayarlari, alan ve gorunum kontrolu.',
            'category' => 'core',
            'status' => 'core',
            'is_core' => true,
            'mandatory' => true,
            'default_enabled' => true,
            'requires_package' => false,
            'parent_module' => null,
            'sort_order' => 120,
        ],
        'product_data_hub' => [
            'key' => 'product_data_hub',
            'label' => 'Product Data Hub',
            'name' => 'Product Data Hub',
            'description' => 'Tedarikci veri kaynaklari, ortak sozlukler ve tenant katalog projection alani.',
            'category' => 'product_data',
            'status' => 'active',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => null,
            'sort_order' => 200,
        ],
        'advanced_catalog' => [
            'key' => 'advanced_catalog',
            'label' => 'Gelismis Katalog',
            'name' => 'Gelismis Katalog',
            'description' => 'Gelismis katalog, varyasyon ve projection yonetimi.',
            'category' => 'product_data',
            'status' => 'active',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => 'product_data_hub',
            'sort_order' => 210,
        ],
        'supplier_feed' => [
            'key' => 'supplier_feed',
            'label' => 'Tedarikci Feed',
            'name' => 'Tedarikci Feed',
            'description' => 'XML/API/CSV kaynakli tedarikci veri beslemeleri.',
            'category' => 'product_data',
            'status' => 'active',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => 'product_data_hub',
            'sort_order' => 220,
        ],
        'xml_import_export' => [
            'key' => 'xml_import_export',
            'label' => 'XML ve CSV Aktarim',
            'name' => 'XML ve CSV Aktarim',
            'description' => 'Iceri/disari veri aktarim omurgasi.',
            'category' => 'integrations',
            'status' => 'planned',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => null,
            'sort_order' => 230,
        ],
        'xml_export' => [
            'key' => 'xml_export',
            'label' => 'XML Export',
            'name' => 'XML Export',
            'description' => 'Dis sistemlere feed ve xml ciktilari.',
            'category' => 'integrations',
            'status' => 'planned',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => 'xml_import_export',
            'sort_order' => 240,
        ],
        'customer_portal' => [
            'key' => 'customer_portal',
            'label' => 'Musteri Portali',
            'name' => 'Musteri Portali',
            'description' => 'Musteri girisi, siparis ve teklif goruntuleme alanlari.',
            'category' => 'portal',
            'status' => 'active',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => null,
            'sort_order' => 250,
        ],
        'quote_customer_approval' => [
            'key' => 'quote_customer_approval',
            'label' => 'Musteri Teklif Onayi',
            'name' => 'Musteri Teklif Onayi',
            'description' => 'Public teklif onayi ve revize isteme akislar.',
            'category' => 'portal',
            'status' => 'active',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => 'customer_portal',
            'sort_order' => 260,
        ],
        'graphic_customer_approval' => [
            'key' => 'graphic_customer_approval',
            'label' => 'Grafik Musteri Onayi',
            'name' => 'Grafik Musteri Onayi',
            'description' => 'Grafik preview dosyalarinin public musteri onay akisleri.',
            'category' => 'portal',
            'status' => 'active',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => 'customer_portal',
            'sort_order' => 270,
        ],
        'notification_center' => [
            'key' => 'notification_center',
            'label' => 'Bildirim Merkezi',
            'name' => 'Bildirim Merkezi',
            'description' => 'SMTP, sablon, kanal ve log yonetimi.',
            'category' => 'notifications',
            'status' => 'active',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => null,
            'sort_order' => 280,
        ],
        'advanced_notifications' => [
            'key' => 'advanced_notifications',
            'label' => 'Gelismis Bildirimler',
            'name' => 'Gelismis Bildirimler',
            'description' => 'Geriye uyumluluk icin korunan, yeni merkez olarak notification_center kullanan moduldur.',
            'category' => 'notifications',
            'status' => 'deprecated',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => 'notification_center',
            'sort_order' => 285,
        ],
        'reporting' => [
            'key' => 'reporting',
            'label' => 'Raporlama',
            'name' => 'Raporlama',
            'description' => 'Gelismis raporlar, analizler ve yonetim ozetleri.',
            'category' => 'reporting',
            'status' => 'active',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => null,
            'sort_order' => 290,
        ],
        'advanced_reports' => [
            'key' => 'advanced_reports',
            'label' => 'Gelismis Raporlar',
            'name' => 'Gelismis Raporlar',
            'description' => 'Geriye uyumluluk icin reporting modulune aliaslanan eski anahtar.',
            'category' => 'reporting',
            'status' => 'deprecated',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => 'reporting',
            'sort_order' => 295,
        ],
        'api_access' => [
            'key' => 'api_access',
            'label' => 'API Erisimi',
            'name' => 'API Erisimi',
            'description' => 'Tenant API tokenlari ve feed API erisimleri.',
            'category' => 'integrations',
            'status' => 'active',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => null,
            'sort_order' => 300,
        ],
        'custom_domain' => [
            'key' => 'custom_domain',
            'label' => 'Ozel Domain',
            'name' => 'Ozel Domain',
            'description' => 'Tenant panel veya portal icin ozel domain kullanimi.',
            'category' => 'advanced',
            'status' => 'planned',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => null,
            'sort_order' => 310,
        ],
        'multi_currency' => [
            'key' => 'multi_currency',
            'label' => 'Coklu Para Birimi',
            'name' => 'Coklu Para Birimi',
            'description' => 'Coklu para birimi is kurallari ve fiyat davranislari.',
            'category' => 'advanced',
            'status' => 'planned',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => 'finance',
            'sort_order' => 320,
        ],
        'production_qc' => [
            'key' => 'production_qc',
            'label' => 'Uretim Kalite Kontrol',
            'name' => 'Uretim Kalite Kontrol',
            'description' => 'Uretim kalite kontrol checklist ve sonuc akislar.',
            'category' => 'advanced',
            'status' => 'planned',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => 'production',
            'sort_order' => 330,
        ],
        'dieline' => [
            'key' => 'dieline',
            'label' => 'Dieline',
            'name' => 'Dieline',
            'description' => 'Kesim kalibi ve kutu tasarim entegrasyonlari.',
            'category' => 'advanced',
            'status' => 'planned',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => null,
            'sort_order' => 340,
        ],
        'accounting_export' => [
            'key' => 'accounting_export',
            'label' => 'Muhasebe Cikisi',
            'name' => 'Muhasebe Cikisi',
            'description' => 'Muhasebe programlarina veri cikisi ve fatura entegrasyonu.',
            'category' => 'integrations',
            'status' => 'planned',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => 'finance',
            'sort_order' => 350,
        ],
        'web_quote_widget' => [
            'key' => 'web_quote_widget',
            'label' => 'Web Teklif Widget',
            'name' => 'Web Teklif Widget',
            'description' => 'Site icine gomulen teklif veya lead toplama widget alanlari.',
            'category' => 'portal',
            'status' => 'passive',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => null,
            'sort_order' => 360,
        ],
        'matbaa' => [
            'key' => 'matbaa',
            'label' => 'Matbaa Modulu',
            'name' => 'Matbaa Modulu',
            'description' => 'Matbaa odakli teklif ve hesap motoru ailesi icin rezerv moduldur.',
            'category' => 'advanced',
            'status' => 'planned',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => null,
            'sort_order' => 370,
        ],
        'retail_sales' => [
            'key' => 'retail_sales',
            'label' => 'Perakende Satis',
            'name' => 'Perakende Satis',
            'description' => 'Perakende siparis ve kasa akislari icin gelecekte kullanilacak modul.',
            'category' => 'advanced',
            'status' => 'planned',
            'is_core' => false,
            'mandatory' => false,
            'default_enabled' => false,
            'requires_package' => true,
            'parent_module' => null,
            'sort_order' => 380,
        ],
    ],

    'features' => [
        'core' => [
            'tenant_access' => [
                'key' => 'tenant_access',
                'label' => 'Tenant Erisimi',
                'name' => 'Tenant Erisimi',
                'description' => 'Tenant panel girisi ve temel erisim akislar.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 10,
            ],
            'dashboard' => [
                'key' => 'dashboard',
                'label' => 'Panel',
                'name' => 'Panel',
                'description' => 'Temel tenant panel gorunumu.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 20,
            ],
            'basic_settings' => [
                'key' => 'basic_settings',
                'label' => 'Temel Ayarlar',
                'name' => 'Temel Ayarlar',
                'description' => 'Tenant genel ayar omurgasi.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 30,
            ],
        ],
        'order_flow' => [
            'promotion_quotes' => [
                'key' => 'promotion_quotes',
                'label' => 'Promosyon Teklifleri',
                'name' => 'Promosyon Teklifleri',
                'description' => 'Promosyon teklif create/edit/show akislari.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 10,
            ],
            'print_quotes' => [
                'key' => 'print_quotes',
                'label' => 'Baski Teklifleri',
                'name' => 'Baski Teklifleri',
                'description' => 'Baski veya matbaa odakli teklif akislar.',
                'status' => 'planned',
                'default_enabled' => false,
                'sort_order' => 20,
            ],
            'quote_to_order' => [
                'key' => 'quote_to_order',
                'label' => 'Tekliften Siparise',
                'name' => 'Tekliften Siparise',
                'description' => 'Onayli teklifin siparise donusumu.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 30,
            ],
            'order_tracking' => [
                'key' => 'order_tracking',
                'label' => 'Siparis Takibi',
                'name' => 'Siparis Takibi',
                'description' => 'Siparis yasam dongusu ve durum izleme.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 40,
            ],
            'quote_send_snapshot' => [
                'key' => 'quote_send_snapshot',
                'label' => 'Teklif Gonderim Snapshot',
                'name' => 'Teklif Gonderim Snapshot',
                'description' => 'Musteriye giden teklif snapshot yapisi.',
                'status' => 'active',
                'default_enabled' => true,
                'sort_order' => 50,
            ],
        ],
        'work_forms' => [
            'work_form_creation' => [
                'key' => 'work_form_creation',
                'label' => 'Is Formu Olusturma',
                'name' => 'Is Formu Olusturma',
                'description' => 'Siparisten is formu olusturma.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 10,
            ],
            'public_work_form_tracking' => [
                'key' => 'public_work_form_tracking',
                'label' => 'Public Is Formu Takibi',
                'name' => 'Public Is Formu Takibi',
                'description' => 'Gizli veri sizdirmadan public takip linkleri.',
                'status' => 'active',
                'default_enabled' => true,
                'sort_order' => 20,
            ],
        ],
        'current_accounts' => [
            'current_account_cards' => [
                'key' => 'current_account_cards',
                'label' => 'Cari Kartlar',
                'name' => 'Cari Kartlar',
                'description' => 'Cari kart listesi ve detaylari.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 10,
            ],
            'current_account_transactions' => [
                'key' => 'current_account_transactions',
                'label' => 'Cari Hareketler',
                'name' => 'Cari Hareketler',
                'description' => 'Cari hareket index, summary ve manuel kayitlar.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 20,
            ],
            'customer_payments' => [
                'key' => 'customer_payments',
                'label' => 'Musteri Tahsilatlari',
                'name' => 'Musteri Tahsilatlari',
                'description' => 'Order payment kayitlarinin cari baglantisi.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 30,
            ],
            'supplier_debits' => [
                'key' => 'supplier_debits',
                'label' => 'Tedarikci Borclari',
                'name' => 'Tedarikci Borclari',
                'description' => 'Procurement kaynakli supplier_debit hareketleri.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 40,
            ],
            'subcontractor_debits' => [
                'key' => 'subcontractor_debits',
                'label' => 'Fason Borclari',
                'name' => 'Fason Borclari',
                'description' => 'Fason uretim kaynakli subcontractor_debit hareketleri.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 50,
            ],
        ],
        'finance' => [
            'payment_tracking' => [
                'key' => 'payment_tracking',
                'label' => 'Odeme Takibi',
                'name' => 'Odeme Takibi',
                'description' => 'Tahsilat kayitlari ve odeme listeleme.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 10,
            ],
            'finance_summary' => [
                'key' => 'finance_summary',
                'label' => 'Finans Ozetleri',
                'name' => 'Finans Ozetleri',
                'description' => 'Siparis ve tenant finans ozetleri.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 20,
            ],
            'view_financial_data' => [
                'key' => 'view_financial_data',
                'label' => 'Finansal Veri Goruntuleme',
                'name' => 'Finansal Veri Goruntuleme',
                'description' => 'Fiyat ve maliyet gorunurlugu icin capability anahtari.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 30,
            ],
            'manage_payments' => [
                'key' => 'manage_payments',
                'label' => 'Odeme Yonetimi',
                'name' => 'Odeme Yonetimi',
                'description' => 'Manuel tahsilat ve odeme islemleri.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 40,
            ],
        ],
        'procurement' => [
            'procurement_queue' => [
                'key' => 'procurement_queue',
                'label' => 'Tedarik Kuyrugu',
                'name' => 'Tedarik Kuyrugu',
                'description' => 'Tedarik is listesi ve durum havuzlari.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 10,
            ],
            'supplier_requests' => [
                'key' => 'supplier_requests',
                'label' => 'Tedarikci Talepleri',
                'name' => 'Tedarikci Talepleri',
                'description' => 'Supplier procurement request akislari.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 20,
            ],
            'supplier_request_print_form' => [
                'key' => 'supplier_request_print_form',
                'label' => 'Tedarik Print Formu',
                'name' => 'Tedarik Print Formu',
                'description' => 'Tedarik is formu veya yazdirma yuzeyleri.',
                'status' => 'active',
                'default_enabled' => true,
                'sort_order' => 30,
            ],
            'supplier_purchase_debits' => [
                'key' => 'supplier_purchase_debits',
                'label' => 'Tedarik Satin Alma Borclari',
                'name' => 'Tedarik Satin Alma Borclari',
                'description' => 'Procurement purchase kalemlerinin cari baglantisi.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 40,
            ],
        ],
        'graphics' => [
            'graphic_queue' => [
                'key' => 'graphic_queue',
                'label' => 'Grafik Kuyrugu',
                'name' => 'Grafik Kuyrugu',
                'description' => 'Grafik operasyon listeleri.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 10,
            ],
            'per_print_graphics' => [
                'key' => 'per_print_graphics',
                'label' => 'Baski Bazli Grafik',
                'name' => 'Baski Bazli Grafik',
                'description' => 'Her baski satiri icin grafik operasyonu.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 20,
            ],
            'customer_visible_files' => [
                'key' => 'customer_visible_files',
                'label' => 'Musteriye Gorunen Dosyalar',
                'name' => 'Musteriye Gorunen Dosyalar',
                'description' => 'Public veya musteri tarafinda gorunebilen grafik dosyalari.',
                'status' => 'active',
                'default_enabled' => true,
                'sort_order' => 30,
            ],
            'paste_upload' => [
                'key' => 'paste_upload',
                'label' => 'Yapistir Yukle',
                'name' => 'Yapistir Yukle',
                'description' => 'Grafik ekraninda hizli gorsel yukleme akislar.',
                'status' => 'active',
                'default_enabled' => true,
                'sort_order' => 40,
            ],
        ],
        'production' => [
            'production_queue' => [
                'key' => 'production_queue',
                'label' => 'Uretim Kuyrugu',
                'name' => 'Uretim Kuyrugu',
                'description' => 'Per-print uretim operasyon listeleri.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 10,
            ],
            'per_print_production' => [
                'key' => 'per_print_production',
                'label' => 'Baski Bazli Uretim',
                'name' => 'Baski Bazli Uretim',
                'description' => 'Her baski satiri icin uretim kaydi.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 20,
            ],
            'partial_completion' => [
                'key' => 'partial_completion',
                'label' => 'Kismi Tamamlama',
                'name' => 'Kismi Tamamlama',
                'description' => 'Kismi basildi ve kalan miktar akislar.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 30,
            ],
            'subcontractor_costs' => [
                'key' => 'subcontractor_costs',
                'label' => 'Fason Maliyetleri',
                'name' => 'Fason Maliyetleri',
                'description' => 'Subcontractor cost ve cari baglanti yuzeyleri.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 40,
            ],
            'setup_readiness' => [
                'key' => 'setup_readiness',
                'label' => 'Hazirlik Readiness',
                'name' => 'Hazirlik Readiness',
                'description' => 'Setup requirement durumunun readiness kararina etkisi.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 50,
            ],
        ],
        'delivery' => [
            'delivery_queue' => [
                'key' => 'delivery_queue',
                'label' => 'Teslimat Kuyrugu',
                'name' => 'Teslimat Kuyrugu',
                'description' => 'Teslimat ve paketleme is listeleri.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 10,
            ],
            'package_koli_tracking' => [
                'key' => 'package_koli_tracking',
                'label' => 'Koli Takibi',
                'name' => 'Koli Takibi',
                'description' => 'Paket ve koli bazli takip akislar.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 20,
            ],
            'delivery_documents' => [
                'key' => 'delivery_documents',
                'label' => 'Teslimat Belgeleri',
                'name' => 'Teslimat Belgeleri',
                'description' => 'Sevk ve teslimat belge yuzeyleri.',
                'status' => 'active',
                'default_enabled' => true,
                'sort_order' => 30,
            ],
            'public_delivery_tracking' => [
                'key' => 'public_delivery_tracking',
                'label' => 'Public Teslimat Takibi',
                'name' => 'Public Teslimat Takibi',
                'description' => 'Guvenli public teslimat takip akislar.',
                'status' => 'active',
                'default_enabled' => true,
                'sort_order' => 40,
            ],
        ],
        'print_settings' => [
            'standard_print_types' => [
                'key' => 'standard_print_types',
                'label' => 'Standart Baski Tipleri',
                'name' => 'Standart Baski Tipleri',
                'description' => 'Global baski tipi sozlugu.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 10,
            ],
            'tenant_print_settings' => [
                'key' => 'tenant_print_settings',
                'label' => 'Tenant Baski Ayarlari',
                'name' => 'Tenant Baski Ayarlari',
                'description' => 'Tenant bazli baski kurallari ve varsayilanlar.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 20,
            ],
            'setup_requirements' => [
                'key' => 'setup_requirements',
                'label' => 'Hazirlik Gereksinimleri',
                'name' => 'Hazirlik Gereksinimleri',
                'description' => 'Order item print setup requirement child kayitlari.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 30,
            ],
            'default_print_price' => [
                'key' => 'default_print_price',
                'label' => 'Varsayilan Baski Fiyati',
                'name' => 'Varsayilan Baski Fiyati',
                'description' => 'Tenant print setting default unit price oneri mantigi.',
                'status' => 'active',
                'default_enabled' => true,
                'sort_order' => 40,
            ],
        ],
        'user_management' => [
            'tenant_users' => [
                'key' => 'tenant_users',
                'label' => 'Tenant Kullanicilari',
                'name' => 'Tenant Kullanicilari',
                'description' => 'Kullanici listeleme ve yonetim akislar.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 10,
            ],
            'roles_permissions' => [
                'key' => 'roles_permissions',
                'label' => 'Rol ve Yetkiler',
                'name' => 'Rol ve Yetkiler',
                'description' => 'Tenant rol ve permission atamalari.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 20,
            ],
        ],
        'tenant_settings' => [
            'general_settings' => [
                'key' => 'general_settings',
                'label' => 'Genel Ayarlar',
                'name' => 'Genel Ayarlar',
                'description' => 'Genel tenant panel ayarlari.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 10,
            ],
            'company_profile' => [
                'key' => 'company_profile',
                'label' => 'Firma Bilgileri',
                'name' => 'Firma Bilgileri',
                'description' => 'Tenant sirket profili ve gosterim bilgileri.',
                'status' => 'core',
                'default_enabled' => true,
                'sort_order' => 20,
            ],
            'package_usage' => [
                'key' => 'package_usage',
                'label' => 'Paket ve Kullanim',
                'name' => 'Paket ve Kullanim',
                'description' => 'Lisans, paket ve kullanim ozeti yuzeyleri.',
                'status' => 'planned',
                'default_enabled' => false,
                'sort_order' => 30,
            ],
        ],
        'product_data_hub' => [
            'supplier_sources' => [
                'key' => 'supplier_sources',
                'label' => 'Tedarikci Kaynaklari',
                'name' => 'Tedarikci Kaynaklari',
                'description' => 'Gercek supplier source ve sync omurgasi.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 10,
            ],
            'standard_categories' => [
                'key' => 'standard_categories',
                'label' => 'Standart Kategoriler',
                'name' => 'Standart Kategoriler',
                'description' => 'Super admin ortak kategori yapisi.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 20,
            ],
            'category_mapping' => [
                'key' => 'category_mapping',
                'label' => 'Kategori Esleme',
                'name' => 'Kategori Esleme',
                'description' => 'Supplier kategori esleme merkezi.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 30,
            ],
            'product_mapping' => [
                'key' => 'product_mapping',
                'label' => 'Urun Esleme',
                'name' => 'Urun Esleme',
                'description' => 'Urun alanlari ve projection mapping akislar.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 40,
            ],
            'tenant_catalog_projection' => [
                'key' => 'tenant_catalog_projection',
                'label' => 'Tenant Katalog Projection',
                'name' => 'Tenant Katalog Projection',
                'description' => 'Tenant katalog yansitma ve cikti akislar.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 50,
            ],
        ],
        'advanced_catalog' => [
            'local_stock' => [
                'key' => 'local_stock',
                'label' => 'Yerel Stok',
                'name' => 'Yerel Stok',
                'description' => 'Tenant lokal stok takibi.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 10,
            ],
            'stock_movements' => [
                'key' => 'stock_movements',
                'label' => 'Stok Hareketleri',
                'name' => 'Stok Hareketleri',
                'description' => 'Stok giris-cikis hareketleri.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 20,
            ],
            'price_management' => [
                'key' => 'price_management',
                'label' => 'Fiyat Yonetimi',
                'name' => 'Fiyat Yonetimi',
                'description' => 'Catalog price management akislar.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 30,
            ],
            'product_variants' => [
                'key' => 'product_variants',
                'label' => 'Urun Varyasyonlari',
                'name' => 'Urun Varyasyonlari',
                'description' => 'Renk, beden ve varyasyon detaylari.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 40,
            ],
        ],
        'supplier_feed' => [
            'supplier_xml_import' => [
                'key' => 'supplier_xml_import',
                'label' => 'Supplier XML Ice Aktarma',
                'name' => 'Supplier XML Ice Aktarma',
                'description' => 'XML feed import capability.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 10,
            ],
            'supplier_csv_import' => [
                'key' => 'supplier_csv_import',
                'label' => 'Supplier CSV Ice Aktarma',
                'name' => 'Supplier CSV Ice Aktarma',
                'description' => 'CSV tabanli supplier import capability.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 20,
            ],
            'supplier_api_integration' => [
                'key' => 'supplier_api_integration',
                'label' => 'Supplier API Entegrasyonu',
                'name' => 'Supplier API Entegrasyonu',
                'description' => 'Supplier API import capability.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 30,
            ],
            'supplier_field_mapping' => [
                'key' => 'supplier_field_mapping',
                'label' => 'Supplier Alan Esleme',
                'name' => 'Supplier Alan Esleme',
                'description' => 'Supplier feed field mapping.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 40,
            ],
            'supplier_sync_scheduling' => [
                'key' => 'supplier_sync_scheduling',
                'label' => 'Supplier Sync Planlama',
                'name' => 'Supplier Sync Planlama',
                'description' => 'Zamanlanmis feed sync capability.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 50,
            ],
        ],
        'xml_import_export' => [
            'xml_import' => [
                'key' => 'xml_import',
                'label' => 'XML Import',
                'name' => 'XML Import',
                'description' => 'Genel XML import capability.',
                'status' => 'planned',
                'default_enabled' => false,
                'sort_order' => 10,
            ],
            'csv_import' => [
                'key' => 'csv_import',
                'label' => 'CSV Import',
                'name' => 'CSV Import',
                'description' => 'Genel CSV import capability.',
                'status' => 'planned',
                'default_enabled' => false,
                'sort_order' => 20,
            ],
            'xml_export' => [
                'key' => 'xml_export',
                'label' => 'XML Export',
                'name' => 'XML Export',
                'description' => 'XML export capability.',
                'status' => 'planned',
                'default_enabled' => false,
                'sort_order' => 30,
            ],
            'feed_outputs' => [
                'key' => 'feed_outputs',
                'label' => 'Feed Ciktilari',
                'name' => 'Feed Ciktilari',
                'description' => 'Harici sistemler icin feed output capability.',
                'status' => 'planned',
                'default_enabled' => false,
                'sort_order' => 40,
            ],
        ],
        'customer_portal' => [
            'customer_login' => [
                'key' => 'customer_login',
                'label' => 'Musteri Girisi',
                'name' => 'Musteri Girisi',
                'description' => 'Portal login capability.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 10,
            ],
            'portal_orders' => [
                'key' => 'portal_orders',
                'label' => 'Portal Siparisleri',
                'name' => 'Portal Siparisleri',
                'description' => 'Portal uzerinden siparis goruntuleme.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 20,
            ],
            'portal_quotes' => [
                'key' => 'portal_quotes',
                'label' => 'Portal Teklifleri',
                'name' => 'Portal Teklifleri',
                'description' => 'Portal uzerinden teklif goruntuleme.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 30,
            ],
        ],
        'quote_customer_approval' => [
            'public_quote_approval' => [
                'key' => 'public_quote_approval',
                'label' => 'Public Teklif Onayi',
                'name' => 'Public Teklif Onayi',
                'description' => 'Public teklif onay formu.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 10,
            ],
            'quote_approval_requests' => [
                'key' => 'quote_approval_requests',
                'label' => 'Teklif Onay Talepleri',
                'name' => 'Teklif Onay Talepleri',
                'description' => 'Teklif gonderim ve token request kayitlari.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 20,
            ],
            'customer_quote_approval' => [
                'key' => 'customer_quote_approval',
                'label' => 'Musteri Teklif Onayi Legacy',
                'name' => 'Musteri Teklif Onayi Legacy',
                'description' => 'Eski feature key geriye uyumluluk icin korunur.',
                'status' => 'deprecated',
                'default_enabled' => false,
                'sort_order' => 99,
            ],
        ],
        'graphic_customer_approval' => [
            'public_graphic_approval' => [
                'key' => 'public_graphic_approval',
                'label' => 'Public Grafik Onayi',
                'name' => 'Public Grafik Onayi',
                'description' => 'Musteri tarafinda grafik onay capability.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 10,
            ],
        ],
        'notification_center' => [
            'smtp_settings' => [
                'key' => 'smtp_settings',
                'label' => 'SMTP Ayarlari',
                'name' => 'SMTP Ayarlari',
                'description' => 'Tenant SMTP konfigrasyonu.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 10,
            ],
            'notification_templates' => [
                'key' => 'notification_templates',
                'label' => 'Bildirim Sablonlari',
                'name' => 'Bildirim Sablonlari',
                'description' => 'Mesaj sablonlari ve icerik yonetimi.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 20,
            ],
            'notification_logs' => [
                'key' => 'notification_logs',
                'label' => 'Bildirim Loglari',
                'name' => 'Bildirim Loglari',
                'description' => 'Bildirim gecmisi ve log kayitlari.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 30,
            ],
            'whatsapp_links' => [
                'key' => 'whatsapp_links',
                'label' => 'WhatsApp Linkleri',
                'name' => 'WhatsApp Linkleri',
                'description' => 'WhatsApp tabanli hizli gonderim capability.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 40,
            ],
        ],
        'reporting' => [
            'sales_analytics' => [
                'key' => 'sales_analytics',
                'label' => 'Satis Analitikleri',
                'name' => 'Satis Analitikleri',
                'description' => 'Satis bazli ileri seviye raporlama.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 10,
            ],
            'profit_analysis' => [
                'key' => 'profit_analysis',
                'label' => 'Karlilik Analizi',
                'name' => 'Karlilik Analizi',
                'description' => 'Karlilik bazli analiz capability.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 20,
            ],
            'customer_analysis' => [
                'key' => 'customer_analysis',
                'label' => 'Musteri Analizi',
                'name' => 'Musteri Analizi',
                'description' => 'Musteri performans raporlari.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 30,
            ],
            'custom_reports' => [
                'key' => 'custom_reports',
                'label' => 'Ozel Raporlar',
                'name' => 'Ozel Raporlar',
                'description' => 'Esnek rapor capability.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 40,
            ],
        ],
        'api_access' => [
            'tenant_api_tokens' => [
                'key' => 'tenant_api_tokens',
                'label' => 'Tenant API Tokenlari',
                'name' => 'Tenant API Tokenlari',
                'description' => 'API anahtari ve token yonetimi.',
                'status' => 'active',
                'default_enabled' => false,
                'sort_order' => 10,
            ],
            'clean_product_feed_api' => [
                'key' => 'clean_product_feed_api',
                'label' => 'Temiz Product Feed API',
                'name' => 'Temiz Product Feed API',
                'description' => 'Disa acilan temiz urun feed API yuzeyi.',
                'status' => 'planned',
                'default_enabled' => false,
                'sort_order' => 20,
            ],
        ],
        'custom_domain' => [
            'tenant_custom_domain' => [
                'key' => 'tenant_custom_domain',
                'label' => 'Tenant Ozel Domain',
                'name' => 'Tenant Ozel Domain',
                'description' => 'Tenant panel veya portal domain atama capability.',
                'status' => 'planned',
                'default_enabled' => false,
                'sort_order' => 10,
            ],
            'domain_verification' => [
                'key' => 'domain_verification',
                'label' => 'Domain Dogrulama',
                'name' => 'Domain Dogrulama',
                'description' => 'DNS veya host dogrulama capability.',
                'status' => 'planned',
                'default_enabled' => false,
                'sort_order' => 20,
            ],
        ],
        'production_qc' => [
            'qc_checklist' => [
                'key' => 'qc_checklist',
                'label' => 'QC Checklist',
                'name' => 'QC Checklist',
                'description' => 'Kalite kontrol checklist capability.',
                'status' => 'planned',
                'default_enabled' => false,
                'sort_order' => 10,
            ],
            'qc_result' => [
                'key' => 'qc_result',
                'label' => 'QC Sonucu',
                'name' => 'QC Sonucu',
                'description' => 'QC sonuc ve durum capability.',
                'status' => 'planned',
                'default_enabled' => false,
                'sort_order' => 20,
            ],
            'qc_photos' => [
                'key' => 'qc_photos',
                'label' => 'QC Fotograflari',
                'name' => 'QC Fotograflari',
                'description' => 'QC fotograflari ve kanit capability.',
                'status' => 'planned',
                'default_enabled' => false,
                'sort_order' => 30,
            ],
            'quality_control' => [
                'key' => 'quality_control',
                'label' => 'Quality Control Legacy',
                'name' => 'Quality Control Legacy',
                'description' => 'Eski key geriye uyumluluk icin korunur.',
                'status' => 'deprecated',
                'default_enabled' => false,
                'sort_order' => 99,
            ],
        ],
    ],

    'aliases' => [
        'modules' => [
            'promotion_orders' => 'order_flow',
            'print_orders' => 'order_flow',
            'customer_quote_approval' => 'quote_customer_approval',
            'advanced_notifications' => 'notification_center',
            'advanced_reports' => 'reporting',
            'quality_control' => 'production_qc',
            'portal' => 'customer_portal',
        ],
        'features' => [
            'quote_management' => 'promotion_quotes',
            'order_management' => 'quote_to_order',
            'basic_reporting' => 'dashboard',
            'customer_quote_approval' => 'public_quote_approval',
            'email_notifications' => 'smtp_settings',
            'notification_rules' => 'notification_logs',
            'quality_control' => 'qc_result',
        ],
    ],

    'default_modules' => [
        'core',
        'order_flow',
        'work_forms',
        'current_accounts',
        'finance',
        'procurement',
        'graphics',
        'production',
        'delivery',
        'print_settings',
        'user_management',
        'tenant_settings',
    ],

    'trial_modules' => [
        'customer_portal',
        'reporting',
    ],
];
