<?php

use App\Models\NotificationTemplate;

return [
    'channels' => [
        'email' => [
            'key' => 'email',
            'label' => 'E-posta',
            'status' => 'active',
        ],
        'whatsapp_link' => [
            'key' => 'whatsapp_link',
            'label' => 'WhatsApp Link',
            'status' => 'active',
        ],
        'internal' => [
            'key' => 'internal',
            'label' => 'İç Bildirim',
            'status' => 'active',
        ],
        'sms' => [
            'key' => 'sms',
            'label' => 'SMS',
            'status' => 'passive',
        ],
    ],

    'status_values' => [
        'pending',
        'sent',
        'failed',
        'skipped',
        'link_created',
        'preview',
        'cancelled',
    ],

    'events' => [
        'quote_created' => [
            'key' => 'quote_created',
            'label' => 'Teklif Oluşturuldu',
            'category' => 'quote',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal'],
            'status' => 'active',
            'description' => 'Yeni teklif kaydı açıldığında tetiklenir.',
            'default_template_subject' => 'Yeni teklif oluşturuldu: {{quote_number}}',
            'default_template_body' => 'Yeni teklif oluşturuldu. Teklif: {{quote_number}} / Müşteri: {{customer_name}}',
        ],
        'quote_sent_to_customer' => [
            'key' => 'quote_sent_to_customer',
            'label' => 'Teklif Müşteriye Gönderildi',
            'category' => 'quote',
            'default_audience' => NotificationTemplate::AUDIENCE_CUSTOMER,
            'allowed_channels' => ['email', 'whatsapp_link', 'internal'],
            'status' => 'active',
            'description' => 'Teklif müşteri paylaşımına hazırlandığında tetiklenir.',
            'default_template_subject' => 'Teklifiniz hazır: {{quote_number}}',
            'default_template_body' => 'Merhaba {{customer_name}}, teklifiniz hazır. Teklif No: {{quote_number}}',
        ],
        'quote_customer_viewed' => [
            'key' => 'quote_customer_viewed',
            'label' => 'Teklif Müşteri Tarafından Görüntülendi',
            'category' => 'quote',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal'],
            'status' => 'active',
            'description' => 'Müşteri teklif public linkini görüntülediğinde tetiklenir.',
            'default_template_subject' => 'Teklif görüntülendi: {{quote_number}}',
            'default_template_body' => 'Müşteri teklif bağlantısını görüntüledi. Teklif: {{quote_number}}',
        ],
        'quote_customer_approved' => [
            'key' => 'quote_customer_approved',
            'label' => 'Teklif Müşteri Tarafından Onaylandı',
            'category' => 'quote',
            'default_audience' => NotificationTemplate::AUDIENCE_ADMIN,
            'allowed_channels' => ['internal'],
            'status' => 'active',
            'description' => 'Müşteri teklifi onayladığında tetiklenir.',
            'default_template_subject' => 'Teklif onaylandı: {{quote_number}}',
            'default_template_body' => 'Teklif müşteri tarafından onaylandı. Teklif: {{quote_number}}',
        ],
        'quote_revision_requested' => [
            'key' => 'quote_revision_requested',
            'label' => 'Teklif İçin Revize İstendi',
            'category' => 'quote',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal'],
            'status' => 'active',
            'description' => 'Müşteri teklif için revize talep ettiğinde tetiklenir.',
            'default_template_subject' => 'Revize talebi: {{quote_number}}',
            'default_template_body' => 'Müşteri teklif için revize istedi. Teklif: {{quote_number}}',
        ],
        'quote_rejected' => [
            'key' => 'quote_rejected',
            'label' => 'Teklif Reddedildi',
            'category' => 'quote',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal'],
            'status' => 'active',
            'description' => 'Müşteri teklifi reddettiğinde tetiklenir.',
            'default_template_subject' => 'Teklif reddedildi: {{quote_number}}',
            'default_template_body' => 'Teklif müşteri tarafından reddedildi. Teklif: {{quote_number}}',
        ],
        'quote_converted_to_order' => [
            'key' => 'quote_converted_to_order',
            'label' => 'Teklif Siparişe Dönüştürüldü',
            'category' => 'quote',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal'],
            'status' => 'active',
            'description' => 'Onaylı teklif siparişe çevrildiğinde tetiklenir.',
            'default_template_subject' => 'Teklif siparişe dönüştü: {{quote_number}}',
            'default_template_body' => 'Teklif siparişe dönüştürüldü. Teklif: {{quote_number}} / Sipariş: {{order_number}}',
        ],
        'graphic_visual_uploaded' => [
            'key' => 'graphic_visual_uploaded',
            'label' => 'Grafik Görseli Yüklendi',
            'category' => 'graphic',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Grafik görseli yüklendiğinde tetiklenir.',
            'default_template_subject' => 'Grafik görseli yüklendi: {{work_form_number}}',
            'default_template_body' => 'Grafik görseli yüklendi. İş Formu: {{work_form_number}} / Ürün: {{product_summary}}',
        ],
        'graphic_customer_approval_requested' => [
            'key' => 'graphic_customer_approval_requested',
            'label' => 'Grafik Müşteri Onayı İstendi',
            'category' => 'graphic',
            'default_audience' => NotificationTemplate::AUDIENCE_CUSTOMER,
            'allowed_channels' => ['email', 'whatsapp_link', 'internal'],
            'status' => 'active',
            'description' => 'Grafik için müşteri onayı istendiğinde tetiklenir.',
            'default_template_subject' => 'Grafik onayınız bekleniyor: {{work_form_number}}',
            'default_template_body' => 'Grafik onayı için bağlantınız hazır. İş Formu: {{work_form_number}}',
        ],
        'graphic_customer_approved' => [
            'key' => 'graphic_customer_approved',
            'label' => 'Grafik Müşteri Tarafından Onaylandı',
            'category' => 'graphic',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal'],
            'status' => 'active',
            'description' => 'Grafik müşteri tarafından onaylandığında tetiklenir.',
            'default_template_subject' => 'Grafik onaylandı: {{work_form_number}}',
            'default_template_body' => 'Grafik müşteri tarafından onaylandı. İş Formu: {{work_form_number}}',
        ],
        'graphic_revision_requested' => [
            'key' => 'graphic_revision_requested',
            'label' => 'Grafik İçin Revize İstendi',
            'category' => 'graphic',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Grafik revize talebi geldiğinde tetiklenir.',
            'default_template_subject' => 'Grafik revize talebi: {{work_form_number}}',
            'default_template_body' => 'Grafik için revize talebi geldi. İş Formu: {{work_form_number}}',
        ],
        'graphic_production_ready' => [
            'key' => 'graphic_production_ready',
            'label' => 'Grafik Üretime Hazır',
            'category' => 'graphic',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Grafik üretime hazır olduğunda tetiklenir.',
            'default_template_subject' => 'Grafik üretime hazır: {{work_form_number}}',
            'default_template_body' => 'Grafik üretime hazır. İş Formu: {{work_form_number}}',
        ],
        'procurement_request_created' => [
            'key' => 'procurement_request_created',
            'label' => 'Tedarik Talebi Oluşturuldu',
            'category' => 'procurement',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Yeni tedarik talebi açıldığında tetiklenir.',
            'default_template_subject' => 'Tedarik talebi oluşturuldu: {{work_form_number}}',
            'default_template_body' => 'Yeni tedarik talebi oluşturuldu. Talep: {{procurement_number}} / İş Formu: {{work_form_number}} / Ürün: {{product_summary}}',
        ],
        'procurement_ordered' => [
            'key' => 'procurement_ordered',
            'label' => 'Tedarik Siparişi Verildi',
            'category' => 'procurement',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Tedarik siparişi verildiğinde tetiklenir.',
            'default_template_subject' => 'Tedarik siparişi verildi: {{procurement_number}}',
            'default_template_body' => 'Tedarik siparişi verildi. Talep: {{procurement_number}} / İş Formu: {{work_form_number}}',
        ],
        'procurement_partially_received' => [
            'key' => 'procurement_partially_received',
            'label' => 'Tedarik Kısmi Teslim Alındı',
            'category' => 'procurement',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Tedarik kısmen teslim alındığında tetiklenir.',
            'default_template_subject' => 'Tedarik kısmi teslim alındı: {{procurement_number}}',
            'default_template_body' => 'Tedarik kısmen teslim alındı. Talep: {{procurement_number}} / Gelen: {{received_quantity}} / Kalan: {{remaining_quantity}}',
        ],
        'procurement_received' => [
            'key' => 'procurement_received',
            'label' => 'Tedarik Tam Teslim Alındı',
            'category' => 'procurement',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Tedarik tamamen teslim alındığında tetiklenir.',
            'default_template_subject' => 'Tedarik teslim alındı: {{procurement_number}}',
            'default_template_body' => 'Tedarik tamamen teslim alındı. Talep: {{procurement_number}} / İş Formu: {{work_form_number}}',
        ],
        'procurement_cancelled' => [
            'key' => 'procurement_cancelled',
            'label' => 'Tedarik İptal Edildi',
            'category' => 'procurement',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Tedarik iptal edildiğinde tetiklenir.',
            'default_template_subject' => 'Tedarik iptal edildi: {{procurement_number}}',
            'default_template_body' => 'Tedarik kaydı iptal edildi. Talep: {{procurement_number}} / İş Formu: {{work_form_number}}',
        ],
        'production_ready' => [
            'key' => 'production_ready',
            'label' => 'Üretim Hazır',
            'category' => 'production',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Üretim başlangıcına hazır olunduğunda tetiklenir.',
            'default_template_subject' => 'Üretim hazır: {{work_form_number}}',
            'default_template_body' => 'Üretim operasyonu hazır. İş Formu: {{work_form_number}} / Ürün: {{product_summary}}',
        ],
        'production_started' => [
            'key' => 'production_started',
            'label' => 'Üretim Başladı',
            'category' => 'production',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Üretim başladığında tetiklenir.',
            'default_template_subject' => 'Üretim başladı: {{work_form_number}}',
            'default_template_body' => 'Üretim başladı. İş Formu: {{work_form_number}} / Baskı: {{print_label}}',
        ],
        'production_partially_completed' => [
            'key' => 'production_partially_completed',
            'label' => 'Üretim Kısmen Tamamlandı',
            'category' => 'production',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Üretim kısmi tamamlandığında tetiklenir.',
            'default_template_subject' => 'Üretim kısmen tamamlandı: {{work_form_number}}',
            'default_template_body' => 'Üretim kısmen tamamlandı. İş Formu: {{work_form_number}} / Basılan: {{completed_quantity}} / Kalan: {{remaining_quantity}}',
        ],
        'production_completed' => [
            'key' => 'production_completed',
            'label' => 'Üretim Tamamlandı',
            'category' => 'production',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Üretim tamamlandığında tetiklenir.',
            'default_template_subject' => 'Üretim tamamlandı: {{work_form_number}}',
            'default_template_body' => 'Üretim tamamlandı. İş Formu: {{work_form_number}} / Ürün: {{product_summary}}',
        ],
        'production_problem_reported' => [
            'key' => 'production_problem_reported',
            'label' => 'Üretim Sorunu Bildirildi',
            'category' => 'production',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Üretim sorunu bildirildiğinde tetiklenir.',
            'default_template_subject' => 'Üretim sorunu: {{work_form_number}}',
            'default_template_body' => 'Üretimde sorun bildirildi. İş Formu: {{work_form_number}} / Baskı: {{print_label}}',
        ],
        'delivery_ready' => [
            'key' => 'delivery_ready',
            'label' => 'Teslimat Hazır',
            'category' => 'delivery',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Teslimat hazır olduğunda tetiklenir.',
            'default_template_subject' => 'Teslimat hazır: {{work_form_number}}',
            'default_template_body' => 'Teslimat hazır. İş Formu: {{work_form_number}} / Yöntem: {{delivery_method}}',
        ],
        'delivery_partially_delivered' => [
            'key' => 'delivery_partially_delivered',
            'label' => 'Teslimat Kısmen Yapıldı',
            'category' => 'delivery',
            'default_audience' => NotificationTemplate::AUDIENCE_CUSTOMER,
            'allowed_channels' => ['email', 'whatsapp_link', 'internal'],
            'status' => 'active',
            'description' => 'Teslimat kısmen tamamlandığında tetiklenir.',
            'default_template_subject' => 'Kısmi teslimat: {{work_form_number}}',
            'default_template_body' => 'Kısmi teslimat kaydedildi. İş Formu: {{work_form_number}} / Teslim edilen: {{delivered_quantity}} / Kalan: {{remaining_quantity}} / Takip: {{tracking_number}}',
        ],
        'delivery_completed' => [
            'key' => 'delivery_completed',
            'label' => 'Teslimat Tamamlandı',
            'category' => 'delivery',
            'default_audience' => NotificationTemplate::AUDIENCE_CUSTOMER,
            'allowed_channels' => ['email', 'whatsapp_link', 'internal'],
            'status' => 'active',
            'description' => 'Teslimat tamamlandığında tetiklenir.',
            'default_template_subject' => 'Teslimat tamamlandı: {{order_number}}',
            'default_template_body' => 'Teslimat tamamlandı. Sipariş: {{order_number}} / Takip: {{public_tracking_url}} / Kargo Takip: {{tracking_number}}',
        ],
        'delivery_problem_reported' => [
            'key' => 'delivery_problem_reported',
            'label' => 'Teslimat Sorunu Bildirildi',
            'category' => 'delivery',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Teslimat sorunu bildirildiğinde tetiklenir.',
            'default_template_subject' => 'Teslimat sorunu: {{order_number}}',
            'default_template_body' => 'Teslimatta sorun bildirildi. İş Formu: {{work_form_number}} / Durum: {{delivery_status}}',
        ],
        'delivery_document_uploaded' => [
            'key' => 'delivery_document_uploaded',
            'label' => 'Teslimat Belgesi Yüklendi',
            'category' => 'delivery',
            'default_audience' => NotificationTemplate::AUDIENCE_INTERNAL,
            'allowed_channels' => ['email', 'whatsapp_link', 'internal'],
            'status' => 'active',
            'description' => 'Teslimat belgesi yüklendiğinde tetiklenir.',
            'default_template_subject' => 'Teslimat belgesi yüklendi: {{order_number}}',
            'default_template_body' => 'Teslimat belgesi yüklendi. İş Formu: {{work_form_number}} / Takip: {{public_tracking_url}}',
        ],
        'payment_received' => [
            'key' => 'payment_received',
            'label' => 'Ödeme Alındı',
            'category' => 'finance',
            'default_audience' => NotificationTemplate::AUDIENCE_FINANCE,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Ödeme kaydedildiğinde tetiklenir.',
            'default_template_subject' => 'Ödeme alındı: {{order_number}}',
            'default_template_body' => 'Ödeme alındı. Sipariş: {{order_number}} / Tutar: {{payment_amount}} {{payment_currency}} / Yöntem: {{payment_method}}',
        ],
        'payment_cancelled' => [
            'key' => 'payment_cancelled',
            'label' => 'Ödeme İptal Edildi',
            'category' => 'finance',
            'default_audience' => NotificationTemplate::AUDIENCE_FINANCE,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Ödeme iptal edildiğinde tetiklenir.',
            'default_template_subject' => 'Ödeme iptal edildi: {{order_number}}',
            'default_template_body' => 'Ödeme iptal edildi. Sipariş: {{order_number}} / Referans: {{payment_reference}}',
        ],
        'payment_due_reminder' => [
            'key' => 'payment_due_reminder',
            'label' => 'Ödeme Vade Hatırlatması',
            'category' => 'finance',
            'default_audience' => NotificationTemplate::AUDIENCE_FINANCE,
            'allowed_channels' => ['internal', 'email'],
            'status' => 'active',
            'description' => 'Vadesi yaklaşan veya geçen ödeme için hatırlatma.',
            'default_template_subject' => 'Vade hatırlatması: {{order_number}}',
            'default_template_body' => 'Ödeme vade hatırlatması. Sipariş: {{order_number}} / Bakiye: {{balance_due}}',
        ],
        'public_tracking_link_shared' => [
            'key' => 'public_tracking_link_shared',
            'label' => 'Public Takip Linki Paylaşıldı',
            'category' => 'tracking',
            'default_audience' => NotificationTemplate::AUDIENCE_CUSTOMER,
            'allowed_channels' => ['email', 'whatsapp_link', 'internal'],
            'status' => 'active',
            'description' => 'Public iş formu takip linki paylaşıldığında tetiklenir.',
            'default_template_subject' => 'Takip bağlantınız hazır',
            'default_template_body' => 'Takip bağlantınız hazır: {{public_tracking_url}}',
        ],
        'customer_visible_attachment_added' => [
            'key' => 'customer_visible_attachment_added',
            'label' => 'Müşteriye Görünür Dosya Eklendi',
            'category' => 'tracking',
            'default_audience' => NotificationTemplate::AUDIENCE_CUSTOMER,
            'allowed_channels' => ['email', 'whatsapp_link', 'internal'],
            'status' => 'active',
            'description' => 'Müşteriye görünür dosya eklendiğinde tetiklenir.',
            'default_template_subject' => 'Yeni dosya eklendi: {{work_form_number}}',
            'default_template_body' => 'Yeni dosya eklendi. İş Formu: {{work_form_number}}',
        ],
    ],

    'aliases' => [
        'quote_sent_email' => 'quote_sent_to_customer',
        'quote_sent_whatsapp' => 'quote_sent_to_customer',
        'graphic_ready_for_production' => 'graphic_production_ready',
        'procurement_created' => 'procurement_request_created',
        'procurement_completed' => 'procurement_received',
        'production_issue_reported' => 'production_problem_reported',
        'delivery_shipped' => 'delivery_partially_delivered',
        'payment_created' => 'payment_received',
        'payment_partial' => 'payment_received',
        'payment_completed' => 'payment_received',
    ],
];
