<?php

return [
    'fetch_security' => [
        'timeout_seconds' => 20,
        'connect_timeout_seconds' => 10,
        'image_timeout_seconds' => 12,
        'max_redirects' => 3,
        'max_preview_bytes' => 25 * 1024 * 1024,
        'max_sync_bytes' => 150 * 1024 * 1024,
        'max_image_bytes' => 8 * 1024 * 1024,
        'block_private_networks' => true,
        'block_localhost' => true,
        'mask_sensitive_query_keys' => true,
    ],

    'assets' => [
        'raw_snapshot_enabled' => env('PDH_RAW_SNAPSHOT_ENABLED', false),
        'image_cache_enabled' => env('PDH_IMAGE_CACHE_ENABLED', false),
        'tenant_export_asset_tracking_enabled' => env('PDH_EXPORT_ASSET_TRACKING_ENABLED', false),
        'types' => [
            'raw_feed_snapshot' => 'Ham Kaynak Dosyasi',
            'preview_upload' => 'Onizleme Dosyasi',
            'sync_log' => 'Senkron Logu',
            'error_sample' => 'Hatali Kayit Ornegi',
            'product_image_original' => 'Urun Orijinal Gorseli',
            'product_image_thumb' => 'Urun Kucuk Gorseli',
            'product_image_pdf' => 'PDF Gorseli',
            'product_image_catalog' => 'Katalog Gorseli',
            'tenant_export' => 'Abone Firma Export Dosyasi',
            'recovery_report' => 'Recovery Raporu',
            'audit_report' => 'Audit Raporu',
        ],
        'disk_map' => [
            'raw_feed_snapshot' => 'pdh_private',
            'preview_upload' => 'pdh_temp',
            'sync_log' => 'pdh_private',
            'error_sample' => 'pdh_private',
            'product_image_original' => 'product_images',
            'product_image_thumb' => 'pdh_public',
            'product_image_pdf' => 'product_images',
            'product_image_catalog' => 'pdh_public',
            'tenant_export' => 'exports',
            'recovery_report' => 'pdh_private',
            'audit_report' => 'pdh_private',
        ],
        'visibility_map' => [
            'raw_feed_snapshot' => 'private',
            'preview_upload' => 'private',
            'sync_log' => 'private',
            'error_sample' => 'private',
            'product_image_original' => 'public',
            'product_image_thumb' => 'public',
            'product_image_pdf' => 'public',
            'product_image_catalog' => 'public',
            'tenant_export' => 'signed',
            'recovery_report' => 'signed',
            'audit_report' => 'signed',
        ],
    ],

    'standard_field_dictionary' => [
        'raw_supplier_product' => [
            'supplier_product_id',
            'parent_supplier_product_id',
            'supplier_product_code',
            'supplier_group_code',
            'supplier_category_slug',
            'product_name',
            'base_product_name',
            'display_product_name',
            'supplier_category_name',
            'description',
            'product_url',
            'detail_url',
            'purchase_price',
            'currency',
            'vat_rate',
            'stock_quantity',
            'total_variant_stock_quantity',
            'parent_image_url',
            'image_url',
            'gallery_images',
            'gallery_image_1',
            'gallery_image_2',
            'gallery_image_3',
            'gallery_image_4',
            'gallery_image_5',
            'image_fallback_used',
            'warning_flag',
        ],
        'raw_supplier_variant' => [
            'variant_id',
            'variant_name',
            'variant_color',
            'variant_stock_code',
            'variant_stock_quantity',
            'variant_image_url',
            'variant_product_url',
            'variant_gallery_images',
            'gallery_images',
            'image_fallback_used',
            'size',
        ],
        'standard_product' => [
            'generated_product_code',
            'generated_variant_code',
            'normalized_product_name',
            'normalized_variant_name',
        ],
    ],

    'preview_warning_messages' => [
        'group_code_as_variant' => 'Grup kodu bulundu, varyasyon olarak işlenecek.',
        'parent_card_found' => 'Parent ürün kartı bulundu.',
        'variant_image_fallback' => 'Varyant görseli yok, ana ürün görseli kullanıldı.',
        'warning_flag_alias' => 'urun_turuncu alanı urun_kirmizi / warning_flag standardına eşlendi.',
        'supplier_special_price_warning' => 'Bu ürün tedarikçi tarafından özel fiyat/iskonto uyarılı işaretlenmiş. Standart indirim uygulanmadan önce kontrol edilmelidir.',
        'code_normalized' => 'Ürün kodu normalize edildi.',
        'prefix_applied' => 'Prefix uygulandı.',
        'required_field_missing' => 'Zorunlu alan eksik.',
        'fallback_to_product_code' => 'urun_id yok, urun_kodu ile eşleştirme yapılacak.',
        'temporary_product_code_generated' => 'Ürün kodu XML’den gelmediği için geçici kod üretildi.',
        'temporary_variant_code_generated' => 'Varyant kodu eşlenmemiş veya boş. Satılabilir varyant ayrımı için Varyant Kodu alanını eşleyin.',
        'missing_product_image' => 'Bu üründe ana görsel de bulunamadı.',
        'wrong_supplier_prefix' => 'Geçici prefix ET görünüyor; kaynak prefix’i EL olmalı.',
    ],

    'supplier_profiles' => [
        'ETKIN' => [
            'display_name' => 'Etkin',
            'supplier_code_prefix' => 'ET',
            'generated_code_template' => '{PREFIX}-{SUPPLIER_GROUP_CODE}',
            'generated_variant_code_template' => '{PREFIX}-{SUPPLIER_PRODUCT_CODE}',
            'generated_name_template' => '{SUPPLIER_PRODUCT_CODE} {PRODUCT_NAME} {VARIANT_COLOR}',
            'product_model' => 'parent_nested_variant',
            'product_node_path' => 'urun',
            'include_parent_as_variant' => true,
            'source_fields' => [
                'urun_id',
                'kategori_id',
                'kategori_adi',
                'urun_kodu',
                'urun_kodgrup',
                'urun_grupkodu',
                'urun_isim',
                'urun_adi',
                'urun_baslik',
                'urun_aciklama',
                'urun_renk',
                'urun_ebat',
                'sira',
                'ozellik',
                'imalat',
                'toplam_stok',
                'urun_stok',
                'urun_fiyat',
                'urun_fiyat_virgul',
                'fiyat_kdv',
                'urun_kdv',
                'kirmiziurun',
                'urun_kirmizi',
                'urun_trase',
                'urun_trase_dosya_isim',
                'urun_trase_dosya_boyut',
                'katalog_sayfa_no',
                'urun_kategori',
                'resim1',
                'resim2',
                'resim3',
                'resim4',
                'resim5',
                'resim6',
                'resim7',
                'resim8',
                'resim9',
                'md5',
                'varyantlar',
            ],
            'field_aliases' => [
                'urun_id' => 'parent_supplier_product_id',
                'kategori_id' => 'supplier_category_id',
                'kategori_adi' => 'supplier_category_name',
                'urun_kodu' => 'supplier_product_code',
                'urun_kodgrup' => 'supplier_group_code',
                'urun_grupkodu' => 'supplier_group_code',
                'urun_isim' => 'product_name',
                'urun_adi' => 'product_name',
                'urun_baslik' => 'display_product_name',
                'urun_aciklama' => 'description',
                'urun_renk' => 'variant_color',
                'urun_ebat' => 'variant_size',
                'toplam_stok' => 'total_variant_stock_quantity',
                'urun_stok' => 'stock_quantity',
                'urun_fiyat' => 'purchase_price',
                'urun_fiyat_virgul' => 'purchase_price_display',
                'fiyat_kdv' => 'vat_rate',
                'urun_kdv' => 'vat_rate',
                'kirmiziurun' => 'warning_flag',
                'urun_kirmizi' => 'warning_flag',
                'urun_trase' => 'artwork_template_url',
                'urun_trase_dosya_isim' => 'artwork_template_file_name',
                'urun_trase_dosya_boyut' => 'artwork_template_file_size',
                'katalog_sayfa_no' => 'supplier_page',
                'urun_kategori' => 'supplier_category_name',
                'resim1' => 'image_url',
                'resim2' => 'gallery_image_2',
                'resim3' => 'gallery_image_3',
                'resim4' => 'gallery_image_4',
                'resim5' => 'gallery_image_5',
                'resim6' => 'gallery_image_6',
                'resim7' => 'gallery_image_7',
                'resim8' => 'gallery_image_8',
                'resim9' => 'gallery_image_9',
                'md5' => 'supplier_hash',
            ],
        ],
        'AKDENIZ' => [
            'display_name' => 'Akdeniz',
            'supplier_code_prefix' => 'AK',
            'generated_code_template' => '{PREFIX}-{SUPPLIER_PRODUCT_CODE}',
            'generated_variant_code_template' => '{PREFIX}-{SUPPLIER_GROUP_CODE}-{VARIANT_COLOR}',
            'generated_name_template' => '{SUPPLIER_PRODUCT_CODE} {PRODUCT_NAME} {VARIANT_COLOR}',
            'product_model' => 'record_variant_row',
            'product_node_path' => 'RECORD',
            'source_fields' => [
                'urun_id',
                'urunkodu',
                'urunattr_id',
                'urunattrgr',
                'urunattradi',
                'urunadi',
                'pure_prodname',
                'listefiyati',
                'listefiyatkapali',
                'iskonto',
                'netfiyat',
                'kur',
                'kdvorani',
                'stokmiktar',
                'stokresim',
                'urunresim',
                'urunresim1',
                'urunresim2',
                'urunresim3',
                'urunresim4',
                'urunresim5',
                'urunresim6',
                'urunresim7',
                'urunresim8',
                'urunresim9',
                'urunresim10',
                'urunresim11',
                'urunresim12',
                'urunresim13',
                'kategori',
                'discat_name',
                'urunaciklamasi',
                'urunbaskifiyatlari',
                'stoktag',
            ],
            'field_aliases' => [
                'urun_id' => 'supplier_product_id',
                'urunkodu' => 'supplier_product_code',
                'urunattr_id' => 'variant_id',
                'urunattrgr' => 'supplier_group_code',
                'urunattradi' => 'variant_name',
                'urunadi' => 'product_name',
                'pure_prodname' => 'base_product_name',
                'listefiyati' => 'list_price',
                'listefiyatkapali' => 'closed_list_price',
                'iskonto' => 'discount_rate',
                'netfiyat' => 'purchase_price',
                'kur' => 'currency',
                'kdvorani' => 'vat_rate',
                'stokmiktar' => 'variant_stock_quantity',
                'stokresim' => 'variant_image_url',
                'urunresim' => 'parent_image_url',
                'urunresim1' => 'image_url',
                'urunresim2' => 'gallery_image_2',
                'urunresim3' => 'gallery_image_3',
                'urunresim4' => 'gallery_image_4',
                'urunresim5' => 'gallery_image_5',
                'urunresim6' => 'gallery_image_6',
                'urunresim7' => 'gallery_image_7',
                'urunresim8' => 'gallery_image_8',
                'urunresim9' => 'gallery_image_9',
                'urunresim10' => 'gallery_image_10',
                'urunresim11' => 'gallery_image_11',
                'urunresim12' => 'gallery_image_12',
                'urunresim13' => 'gallery_image_13',
                'kategori' => 'supplier_category_name',
                'discat_name' => 'supplier_category_name',
                'urunaciklamasi' => 'description',
                'urunbaskifiyatlari' => 'print_price_info_html',
                'stoktag' => 'supplier_tags',
            ],
        ],
        'ILPEN' => [
            'display_name' => 'İlpen',
            'supplier_code_prefix' => 'IL',
            'generated_code_template' => '{PREFIX}-{SUPPLIER_GROUP_CODE}',
            'generated_variant_code_template' => '{PREFIX}-{VARIANT_STOCK_CODE}',
            'generated_name_template' => '{PRODUCT_NAME} {VARIANT_COLOR}',
            'product_model' => 'parent_nested_variant',
            'product_node_path' => 'Urun',
            'source_fields' => [
                'UrunKartiID',
                'UrunAdi',
                'UrunGrupKodu',
                'ResimUrl',
                'UrunUrl',
                'KategoriMain',
                'KategoriSub',
                'AlisFiyati',
                'SatisFiyati',
                'IndirimliFiyat',
                'KdvOrani',
                'ParaBirimi',
                'TumVaryantToplamStokAdedi',
                'VaryasyonID',
                'StokKodu',
                'StokAdedi',
                'EkSecenekOzellik.Ozellik[Tanim=Renk]',
                'VaryasyonResim',
            ],
            'field_aliases' => [
                'UrunKartiID' => 'parent_supplier_product_id',
                'UrunAdi' => 'product_name',
                'UrunGrupKodu' => 'supplier_group_code',
                'ResimUrl' => 'parent_image_url',
                'UrunUrl' => 'product_url',
                'KategoriMain' => 'supplier_category_name',
                'KategoriSub' => 'supplier_subcategory_name',
                'AlisFiyati' => 'purchase_price',
                'SatisFiyati' => 'list_price',
                'IndirimliFiyat' => 'discounted_price',
                'KdvOrani' => 'vat_rate',
                'ParaBirimi' => 'currency',
                'TumVaryantToplamStokAdedi' => 'total_variant_stock_quantity',
                'VaryasyonID' => 'variant_id',
                'StokKodu' => 'variant_stock_code',
                'StokAdedi' => 'variant_stock_quantity',
                'EkSecenekOzellik.Ozellik[Tanim=Renk]' => 'variant_color',
                'VaryasyonResim' => 'variant_image_url',
            ],
        ],
        'YENI-NESIL' => [
            'display_name' => 'Yeni Nesil',
            'supplier_code_prefix' => 'YN',
            'generated_code_template' => '{PREFIX}-{SUPPLIER_PRODUCT_CODE}',
            'generated_variant_code_template' => '{PREFIX}-{SUPPLIER_GROUP_CODE}-{COLOR}',
            'generated_name_template' => '{SUPPLIER_PRODUCT_CODE} {PRODUCT_NAME} {VARIANT_COLOR}',
            'product_model' => 'flat_group_variant',
            'product_node_path' => 'urunler',
            'enrich_gallery_from_product_page_supported' => true,
            'product_page_gallery_hints' => [
                'urunresimleri',
                '/img/',
                'product',
            ],
            'source_fields' => [
                'uid',
                'kid',
                'kid_seviye',
                'kategori',
                'isim',
                'baslik',
                'aciklama',
                'kod',
                'kodgrup',
                'stokkod',
                'sira',
                'renk',
                'ebat',
                'turuncu',
                'opsiyon',
                'stok',
                'imalat',
                'mstok',
                'tstok',
                'istok',
                'toplamstok',
                'sayfa',
                'durum',
                'resim1',
                'resim2',
                'resim3',
                'resim4',
                'resim5',
                'resim6',
                'resim7',
                'resim8',
                'resim9',
                'fiyat',
                'dolar_fiyat',
                'kdv',
            ],
            'field_aliases' => [
                'uid' => 'supplier_product_id',
                'kid' => 'supplier_category_id',
                'kid_seviye' => 'supplier_category_level',
                'kategori' => 'supplier_category_name',
                'isim' => 'product_name',
                'baslik' => 'display_product_name',
                'aciklama' => 'description',
                'kod' => 'supplier_product_code',
                'kodgrup' => 'supplier_group_code',
                'stokkod' => 'variant_stock_code',
                'renk' => 'variant_color',
                'ebat' => 'variant_size',
                'opsiyon' => 'option_name',
                'stok' => 'variant_stock_quantity',
                'imalat' => 'production_flag',
                'toplamstok' => 'total_variant_stock_quantity',
                'sayfa' => 'supplier_page',
                'durum' => 'supplier_status',
                'resim1' => 'image_url',
                'resim2' => 'gallery_image_2',
                'resim3' => 'gallery_image_3',
                'resim4' => 'gallery_image_4',
                'resim5' => 'gallery_image_5',
                'resim6' => 'gallery_image_6',
                'resim7' => 'gallery_image_7',
                'resim8' => 'gallery_image_8',
                'resim9' => 'gallery_image_9',
                'fiyat' => 'list_price',
                'dolar_fiyat' => 'alternative_price',
                'kdv' => 'vat_rate',
                'turuncu' => 'warning_flag',
            ],
        ],
        'POZITRON_JSON' => [
            'display_name' => 'Pozitron JSON',
            'description' => 'Pozitron Promosyon JSON/API kaynağı için parent + varyant yapısı ve USD liste fiyatı standardı.',
            'profile_identity_key' => 'POZITRON',
            'ui_source_type' => 'json',
            'default_url' => 'https://pozitronpromosyon.com/wp-json/public-api/v1/urunler?all=1',
            'suggested_source_name' => 'Pozitron Promosyon JSON',
            'suggested_supplier_name' => 'Pozitron Promosyon',
            'supplier_code_prefix' => 'PZ',
            'generated_code_template' => '{PREFIX}-{SUPPLIER_PRODUCT_CODE}',
            'generated_variant_code_template' => '{PREFIX}-{VARIANT_STOCK_CODE}',
            'generated_name_template' => '{PRODUCT_NAME} {VARIANT_COLOR}',
            'product_model' => 'parent_nested_variant_json',
            'currency' => 'USD',
            'pricing_policy_type' => 'list_price',
            'allowed_ui_source_types' => ['json', 'api'],
            'items_path' => null,
            'product_node_path' => null,
            'source_fields' => [
                'id',
                'urun_sku',
                'urun_adi',
                'urun_aciklamasi',
                'urun_url',
                'kategoriler.0.id',
                'kategoriler.0.ad',
                'kategoriler.0.slug',
                'urun_fiyati',
                'kdv_orani',
                'urun_gorselleri.0',
                'urun_gorselleri',
                'stok_adedi',
                'stok_kaynagi.tip',
                'bilesenler',
                'varyasyonlar',
                'varyasyon_id',
                'stok_kodu',
                'renk',
                'nitelikler.pa_renk',
                'stok_adedi',
                'fiyat',
                'fiyat_normal',
                'gorseller.0',
                'gorseller',
                'urun_url',
            ],
            'field_aliases' => [
                'id' => 'supplier_product_id',
                'urun_sku' => 'supplier_product_code',
                'urun_adi' => 'product_name',
                'urun_aciklamasi' => 'description',
                'urun_url' => 'product_url',
                'kategoriler.0.id' => 'supplier_category_id',
                'kategoriler.0.ad' => 'supplier_category_name',
                'kategoriler.0.slug' => 'supplier_category_slug',
                'urun_fiyati' => 'list_price',
                'kdv_orani' => 'vat_rate',
                'urun_gorselleri.0' => 'image_url',
                'urun_gorselleri' => 'gallery_images',
                'varyasyon_id' => 'variant_id',
                'stok_kodu' => 'variant_stock_code',
                'renk' => 'variant_color',
                'nitelikler.pa_renk' => 'variant_color',
                'stok_adedi' => 'variant_stock_quantity',
                'fiyat' => 'list_price',
                'fiyat_normal' => 'list_price',
                'gorseller.0' => 'variant_image_url',
                'gorseller' => 'variant_gallery_images',
            ],
        ],
    ],
];
